name: Validate student contribution

on:
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven' 
      - name: Build and test with Maven
        run: mvn --batch-mode --update-snapshots clean test
        working-directory: ./LabJavaIO
